# Generated by Django 4.2.2 on 2023-06-30 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=myprofile.models.profile_avatar_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
