# Generated by Django 4.2.2 on 2023-07-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='product',
        ),
        migrations.AlterField(
            model_name='productsale',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myshop.product'),
        ),
    ]
