# Generated by Django 4.2.2 on 2023-07-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_remove_productsale_product_alter_productsale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myshop.product'),
        ),
    ]
