# Generated by Django 4.2.2 on 2023-07-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_subcategory_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
