# Generated by Django 4.2.2 on 2023-07-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_rename_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specification',
            new_name='specifications',
        ),
    ]
