# Generated by Django 4.2.2 on 2023-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='product_image', to='myshop.image'),
        ),
    ]
