# Generated by Django 4.2.2 on 2023-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_sale_image', to='myshop.image'),
        ),
    ]
