# Generated by Django 4.2.2 on 2023-07-03 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_rename_specification_product_specifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_time',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myshop.product'),
        ),
    ]
